### ISSUE TITLE
Missing dependency on `httpretty`

### ISSUE THREAD

**Issue by mjuric** [conda-forge/ads-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The pypi package from which the conda package is built depends on `httpready` (see https://github.com/andycasey/ads/blob/master/requirements.txt, which is loaded by `setup,py`). The conda package, however, doesn't (e.g. check out https://github.com/conda-forge/ads-feedstock/blob/63d7a8f966abd4ed7a382eac792950f802cdb00d/recipe/meta.yaml#L26).

This means that when a package that depends on `ads` is installed from conda-forge, it doesn't bring in `httpready`. When that package subsequently runs `pip check`, pip check returns an error because of the missing dependency.

Proposed solution(s):
- simple: add `httpready` to run requirements in meta.yaml
- better: as httpready only seems to be used for tests, rework upstream `setup.py` to install it only in .[test] installs

### Installed packages

```shell
-
```

### Environment info

```shell
-
```

**Comment by pkgw** [comment]
Could I persuade you to file an issue/PR upstream to alert Andy? It looks like he's keeping the package fairly well-maintained so hopefully we can get a new release with your "better" solution promptly.

**Comment by andycasey** [comment]
I think this has been fixed from my end. I'll leave it for @mjuric to close both issues if it is truly resolved.

**Comment by mjuric** [comment]
I'm confirming this works, thanks!
